import type { OutlineWeight, TileStyleId } from './types';

/**
 * Tile-style registry.
 *
 * ---------------------------------------------------------------------------
 * TO ADD A NEW VISUAL STYLE
 * ---------------------------------------------------------------------------
 * 1. Add an entry to `TILE_STYLES` below.
 * 2. Add matching artwork keys to the tiles in `tiles.ts` and the ports in
 *    `ports.ts` (both are keyed by style id).
 *
 * The style picker in the settings panel is built from this registry, so a new
 * style shows up in the UI automatically.
 */

/** One stroke pass of a coastline. Passes are drawn in array order. */
export interface OutlineLayer {
    stroke: string;
    width: number;
    opacity?: number;
    /** Gaussian blur applied to this pass, for a soft glow. */
    blurStdDeviation?: number;
}

export interface TileStyle {
    id: TileStyleId;
    label: string;
    /** Full-page background behind the board. */
    background: string;
    /** Border drawn around every land hex. */
    tileBorder: {
        stroke: string;
        width: number;
        blurStdDeviation?: number;
    };
    /** Thin outline drawn around every sea hex. */
    waterBorder: {
        stroke: string;
        width: number;
    };
    /** Stroke passes per outline weight. */
    outlines: Record<OutlineWeight, OutlineLayer[]>;
    /** How port boats are drawn. */
    port: {
        /** Boat size as a multiple of hex width. */
        sizeFactor: number;
        /** 'art' uses per-port boat images; 'overlay' stamps a logo on `baseImage`. */
        mode: 'art' | 'overlay';
        baseImage?: string;
        /** Overlay position on the boat, as CSS percentages. */
        logoPosition?: { top: string; left: string };
    };
}

const PARCHMENT = '#E6D7AA';

export const TILE_STYLES: Record<TileStyleId, TileStyle> = {
    classic: {
        id: 'classic',
        label: 'Classic',
        background: '/images/catan_water.png',
        // A single soft-edged stroke. The earlier radial-gradient border is in
        // git history if the layered look is ever wanted back.
        tileBorder: { stroke: PARCHMENT, width: 13, blurStdDeviation: 3 },
        waterBorder: { stroke: '#bfdbfe', width: 1.5 },
        outlines: {
            board: [
                { stroke: PARCHMENT, width: 8, opacity: 0.2 },
                { stroke: PARCHMENT, width: 25, blurStdDeviation: 8 },
            ],
            island: [
                { stroke: PARCHMENT, width: 6, opacity: 0.25 },
                { stroke: PARCHMENT, width: 20, blurStdDeviation: 6 },
            ],
        },
        port: { sizeFactor: 1.4, mode: 'art' },
    },
    simple: {
        id: 'simple',
        label: 'Simple',
        background: '/images/catan_water_style.jpg',
        tileBorder: { stroke: PARCHMENT, width: 13 },
        waterBorder: { stroke: '#bfdbfe', width: 1.5 },
        outlines: {
            board: [{ stroke: PARCHMENT, width: 15 }],
            island: [{ stroke: PARCHMENT, width: 15 }],
        },
        port: {
            sizeFactor: 1.2,
            mode: 'overlay',
            baseImage: '/images/catan_boat_style.png',
            logoPosition: { top: '68%', left: '53%' },
        },
    },
    nights: {
        id: 'nights',
        label: 'Dangerous Nights',
        // The whole board after dark. Terrain is nearly black and everything
        // that separates one thing from another — hex rims, coastlines, the
        // harbour boats — is a lit neon tube instead of a painted line.
        // Artwork is generated by `scripts/generate-dangerous-nights-pack.js`.
        background: '/images/catan_water_nights.png',
        // Dimmer than the coastline on purpose: if every hex seam is as hot
        // as the shoreline the landmass loses its edge entirely.
        tileBorder: { stroke: '#A855F7', width: 7, blurStdDeviation: 4 },
        waterBorder: { stroke: '#3F2C63', width: 1.2 },
        // Wide soft pass first, tight bright core over it: the two together are
        // what read as a tube of light rather than a fat blurry stroke.
        outlines: {
            board: [
                { stroke: '#22D3EE', width: 26, opacity: 0.32, blurStdDeviation: 10 },
                { stroke: '#A5F3FC', width: 6, opacity: 0.85 },
            ],
            island: [
                { stroke: '#FF2D95', width: 24, opacity: 0.45, blurStdDeviation: 9 },
                { stroke: '#FBCFE8', width: 7, opacity: 0.95 },
            ],
        },
        port: {
            // The art occupies about a third of its canvas (see the generator),
            // so this is larger than it looks — it puts the boat on screen at
            // the same 0.62 hex-widths across as the Classic and Simple packs.
            sizeFactor: 1.66,
            mode: 'overlay',
            baseImage: '/images/catan_boat_nights.png',
            logoPosition: { top: '79%', left: '46%' },
        },
    },
    halloween: {
        id: 'halloween',
        label: 'All Hallows',
        // A board that has gone bad. Terrain is rotten and mostly unlit; what
        // light there is comes off a blood moon, a lantern, or something's
        // eyes. Hex rims are bone, and the shoreline bleeds.
        // Artwork is generated by `scripts/generate-halloween-pack.js`.
        background: '/images/catan_water_halloween.png',
        tileBorder: { stroke: '#C9C0A6', width: 8, blurStdDeviation: 2 },
        waterBorder: { stroke: '#2C3A2C', width: 1.2 },
        // Painted, not lit. A wide dark edge with a solid line inside it —
        // a soft wide pass over a bright core is what makes a coastline read
        // as a neon tube, and this pack is not that.
        outlines: {
            board: [
                { stroke: '#241C10', width: 28, opacity: 0.85, blurStdDeviation: 2 },
                { stroke: '#B8AE92', width: 9, opacity: 0.9 },
            ],
            island: [
                { stroke: '#2A0608', width: 32, opacity: 0.9, blurStdDeviation: 2 },
                { stroke: '#9E121C', width: 12, opacity: 0.95 },
            ],
        },
        port: {
            // Same boat geometry as Nights — see `portCorners` in the
            // generator, which derives the mooring lines from this number.
            sizeFactor: 1.66,
            mode: 'overlay',
            baseImage: '/images/catan_boat_halloween.png',
            logoPosition: { top: '79%', left: '46%' },
        },
    },
};

export const DEFAULT_TILE_STYLE: TileStyleId = 'classic';

export function getTileStyle(id: TileStyleId): TileStyle {
    return TILE_STYLES[id] ?? TILE_STYLES[DEFAULT_TILE_STYLE];
}

export function listTileStyles(): TileStyle[] {
    return Object.values(TILE_STYLES);
}
